"""
Django settings for ellington_web project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', "tiddlywinks")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=1))

#ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(" ")
ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'grappelli',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.gis",
    # Required by apps.engine_rules.EngineRule's ArrayField columns
    # (quality_binding, applicability_reasons). The system check fails
    # with postgres.E005 if ArrayField is used without this.
    "django.contrib.postgres",
    "rest_framework",
    'rest_framework_gis',
    "apps.core",
    "apps.styles",
    "apps.charts",
    "apps.practice",
    "apps.engine_rules",
    "apps.rule_review",
    "apps.voicings",
    "apps.audio",
    # Wagtail (#190 epic / #191 spike). Order matters: contrib + core
    # before our cms app. Wagtail's modelcluster + taggit are
    # transitive dependencies that need explicit registration.
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "apps.cms",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise must sit immediately after SecurityMiddleware so static
    # files are served directly from the Daphne process — there is no
    # nginx sidecar in the k8s deployment.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.core.auth.middleware.AuthentikHeaderMiddleware',
    # CurrentUserMiddleware must sit AFTER any auth middleware so
    # request.user is populated. Used by apps.core.signals to attribute
    # role-promotion audit rows to the request user (#131).
    'apps.core.middleware.CurrentUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Baseline security headers (#227): CSP, Permissions-Policy,
    # Referrer-Policy, X-Content-Type-Options. Late in the chain so
    # response is fully assembled before we annotate.
    'apps.core.middleware.SecurityHeadersMiddleware',
    # Wagtail redirect middleware (#191) — must sit AFTER auth so
    # logged-in user context is available for permission-aware
    # redirects. Handles editor-defined permanent redirects without
    # us writing custom views.
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

# Security headers (#227) — override per-env in deployment.
# Setting any to None or "" disables that header.
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

AUTHENTICATION_BACKENDS = [
    "apps.core.auth.backends.AuthentikRemoteUserBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# When True, trust X-authentik-* headers (production behind the Authentik outpost).
# When False (default), the AuthentikHeaderMiddleware is a no-op so local dev
# without Authentik in front can't be tricked by spoofed headers.
AUTHENTIK_HEADER_TRUST = bool(int(os.environ.get("AUTHENTIK_HEADER_TRUST", "0")))

# Django 4.0+ requires the request Origin host (sent by browsers on cross-origin
# POSTs, including any TLS-terminating reverse proxy) to be in this allowlist
# before CSRF tokens validate. Env-driven so dev / staging / prod can each
# carry their own host. Comma-separated, scheme-included
# (https://ellington.siegeanalytics.com).
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]

# WhiteNoise hashes static asset filenames and serves them with
# Cache-Control: max-age=1y — gives admin static a real CDN-like profile
# even without one in front.
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'ellington_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ellington_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

SPATIALITE_LIBRARY_PATH = '/usr/local/lib/mod_spatialite.dylib'
DATABASES = {
    "default": {
        #"ENGINE": os.environ.get("SQL_ENGINE", "django.contrib.gis.db.backends.spatialite"),
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        # "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
        "NAME": os.environ.get('SQL_DATABASE', None),
        "USER": os.environ.get("SQL_USER", None),
        "PASSWORD": os.environ.get("SQL_PASSWORD", None),
        "HOST": os.environ.get("SQL_HOST", None),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (user uploads — practice-flow Recordings, etc.). MEDIA_ROOT
# in production points at a PVC mount in the pod; local dev defaults to
# ``./media/`` under BASE_DIR so a fresh checkout doesn't crash.
# ``MEDIA_URL`` is served by Daphne in dev and by the deployment's static
# server in production (separate from STATIC_URL because user uploads are
# never bundled with the application image).
MEDIA_URL = "/media/"
MEDIA_ROOT = os.environ.get("MEDIA_ROOT", str(BASE_DIR / "media"))

# After login, redirect users to the practice session list. They can
# navigate elsewhere from there. Used by ``@login_required`` and the
# auth login view.
LOGIN_REDIRECT_URL = "/practice/sessions/"
LOGIN_URL = "/accounts/login/"

# Email — DreamHost SMTP per epic #96 sub-ticket (l) / #101. The
# `dheeraj@dheerajchand.com` mailbox is reused from the Resume Generator
# product (resume-generator-manifests PR #1 set the pattern). In DEBUG
# (local dev) we default to the console backend so password resets and
# invite emails print to stdout instead of accidentally hitting the
# DreamHost SMTP. Production env supplies real EMAIL_* vars from the
# ``ellington-config`` ConfigMap + ``ellington-email`` Secret.
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend" if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.dreamhost.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = bool(int(os.environ.get("EMAIL_USE_TLS", "1")))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get(
    "FROM_EMAIL", "dheeraj@dheerajchand.com",
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# Reply-to is set per-message via the EmailMessage `reply_to` kwarg;
# kept here for templates / management commands that want the canonical
# value without rebuilding it.
REPLY_TO_EMAIL = os.environ.get("REPLY_TO_EMAIL", "dheeraj.chand@gmail.com")


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Grappelli Configuration
GRAPPELLI_ADMIN_TITLE = "Ellington"
GRAPPELLI_ADMIN_HEADLINE = "Ellington — Practice Feedback"
GRAPPELLI_SWITCH_USER = True

# Wagtail Configuration (#190 epic / #191 spike) ------------------------
# WAGTAIL_SITE_NAME shows in the admin top-bar; the public-visible URL
# is configured via WAGTAILADMIN_BASE_URL for emails / absolute links.
WAGTAIL_SITE_NAME = "Ellington"
WAGTAILADMIN_BASE_URL = os.environ.get(
    "WAGTAILADMIN_BASE_URL", "https://ellington.siegeanalytics.com",
)
# Default DB-backed search avoids an Elasticsearch dependency. Postgres-
# specific search backend is wired in a later child of #190 once we have
# real content to search.
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    },
}
# Wagtail-managed permitted file extensions for the documents app.
# Spike-conservative; expanded as needs land.
WAGTAILDOCS_EXTENSIONS = ["csv", "docx", "pdf", "txt"]