# Generated by Django 5.2.14 on 2026-06-18 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(help_text='The pedagogue who responded. PROTECT — preserve ground-truth verdicts on user deletion via the sentinel-user anonymize path (apps.core.delete_user_account).', on_delete=django.db.models.deletion.PROTECT, related_name='rule_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
