# Generated by Django 5.2.14 on 2026-06-11 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="A, A', B, intro, outro, vamp, coda, ...", max_length=32)),
                ('order_index', models.PositiveSmallIntegerField(help_text="0-based order within the song's form.")),
                ('measure_count', models.PositiveSmallIntegerField(blank=True, help_text="Number of measures in this section. May be left null when ingesting from a source that doesn't carry it.", null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['song', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('composer', models.CharField(blank=True, max_length=255)),
                ('lyricist', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=8)),
                ('time_signature', models.CharField(blank=True, default='4/4', max_length=8)),
                ('default_tempo_bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('form', models.CharField(blank=True, max_length=64)),
                ('import_source', models.CharField(choices=[('real-book-v1', 'Real Book Vol 1'), ('real-book-v2', 'Real Book Vol 2'), ('real-book-v3', 'Real Book Vol 3'), ('new-real-book', 'New Real Book'), ('ireal-pro', 'iReal Pro forum import'), ('sibelius', 'Sibelius export'), ('musescore', 'MuseScore export'), ('hand-entered', 'Hand-entered'), ('other', 'Other / unknown')], default='other', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Songbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_section', models.PositiveSmallIntegerField(help_text='1-based measure index within the section.')),
                ('time_signature_override', models.CharField(blank=True, help_text="Only set when this measure differs from the song's default (e.g. one 2/4 bar in a 4/4 song).", max_length=8)),
                ('repeat_marker', models.CharField(blank=True, max_length=16)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='charts.section')),
            ],
            options={
                'ordering': ['section', 'number_in_section'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='charts.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='songbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='charts.songbook'),
        ),
        migrations.CreateModel(
            name='ChordEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat', models.DecimalField(decimal_places=2, help_text="1-indexed beat within the measure. 1.0 = downbeat; 2.5 = 'and' of beat 2.", max_digits=4)),
                ('chord_symbol', models.CharField(help_text="Free-form chord symbol — 'Cmaj7', 'Dm7b5', 'G7#9b13', etc.", max_length=32)),
                ('duration_beats', models.DecimalField(blank=True, decimal_places=2, help_text="Beats this chord sounds for. Often inferred from the next ChordEvent's beat; null = 'until next event or end of measure'.", max_digits=4, null=True)),
                ('voicing_reference', models.JSONField(blank=True, default=dict, help_text="Forward-compatible voicing pointer. v0 shape: {} (no opinion). Future shapes: {'voicing_id': '<plugin slug>'} or {'voicing_style_tags': [...]} for soft binding.")),
                ('notes', models.TextField(blank=True)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chord_events', to='charts.measure')),
            ],
            options={
                'ordering': ['measure', 'beat'],
                'constraints': [models.UniqueConstraint(fields=('measure', 'beat'), name='unique_chord_event_per_beat')],
            },
        ),
        migrations.AddConstraint(
            model_name='measure',
            constraint=models.UniqueConstraint(fields=('section', 'number_in_section'), name='unique_measure_per_section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('song', 'order_index'), name='unique_section_order_per_song'),
        ),
    ]
