# Generated by Django 5.2.14 on 2026-06-18 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_alter_chartcomment_author'),
        ('practice', '0008_alter_invite_email_alter_invite_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='songbook',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Creator. Null for canonical seed Songbooks (visibility is forced to public for those).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songbooks_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songbook',
            name='studio',
            field=models.ForeignKey(blank=True, help_text='Used when visibility=studio: members of this Studio gain access. Ignored otherwise.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songbooks', to='practice.studio'),
        ),
        migrations.AddField(
            model_name='songbook',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private (owner + share recipients)'), ('studio', 'Studio (members of linked Studio)'), ('public', 'Public (any signed-in user)')], db_index=True, default='public', max_length=16),
        ),
        migrations.CreateModel(
            name='SongbookShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_note', models.TextField(blank=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songbook_shares_received', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songbook_shares_sent', to=settings.AUTH_USER_MODEL)),
                ('songbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='charts.songbook')),
            ],
            options={
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['recipient', '-shared_at'], name='songbookshare_recipient_idx')],
                'constraints': [models.UniqueConstraint(fields=('songbook', 'recipient'), name='songbookshare_book_recipient_unique')],
            },
        ),
    ]
