# Generated by Django 5.2.14 on 2026-06-11 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0002_idiom_extra_master_extra_style_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('achieved', 'Achieved'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_idiom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeting_goals', to='styles.idiom')),
                ('target_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeting_goals', to='styles.master')),
                ('target_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeting_goals', to='styles.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Optional override for user.first_name + last_name.', max_length=128)),
                ('instrument', models.CharField(choices=[('guitar', 'Guitar'), ('bass', 'Bass guitar'), ('piano', 'Piano'), ('sax', 'Saxophone'), ('trumpet', 'Trumpet'), ('drums', 'Drums'), ('vocals', 'Voice'), ('other', 'Other')], default='guitar', max_length=16)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='intermediate', max_length=16)),
                ('bio', models.TextField(blank=True)),
                ('timezone', models.CharField(blank=True, default='UTC', help_text="IANA TZ identifier (e.g. 'America/Chicago').", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_idioms', models.ManyToManyField(blank=True, related_name='preferring_users', to='styles.idiom')),
                ('preferred_masters', models.ManyToManyField(blank=True, related_name='preferring_users', to='styles.master')),
                ('preferred_styles', models.ManyToManyField(blank=True, related_name='preferring_users', to='styles.style')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
