# Generated by Django 5.2.14 on 2026-06-18 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_directmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePromotionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_username', models.CharField(help_text='Denormalized snapshot of target_user.username at the time of the change.', max_length=150)),
                ('promoted_by_username', models.CharField(blank=True, help_text="Denormalized snapshot of promoted_by.username (or 'system' for non-user-initiated changes).", max_length=150)),
                ('field_name', models.CharField(db_index=True, help_text="Which field changed — e.g. 'is_pedagogue', 'is_staff'.", max_length=64)),
                ('old_value', models.BooleanField()),
                ('new_value', models.BooleanField()),
                ('reason', models.TextField(blank=True, help_text='Optional reason captured at the call site.')),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_by', models.ForeignKey(blank=True, help_text='The admin who flipped the field. Null when set by a management command / migration / system task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_promotions_initiated', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='The user whose role flipped.', on_delete=django.db.models.deletion.PROTECT, related_name='role_promotions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-promoted_at'],
                'indexes': [models.Index(fields=['target_user', '-promoted_at'], name='rolepromo_target_recent_idx')],
            },
        ),
    ]
