# Generated by Django 5.2.14 on 2026-06-10 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('schema_version', models.CharField(default='v1', max_length=16)),
                ('performance_context_metadata', models.JSONField(blank=True, default=dict)),
                ('is_placeholder', models.BooleanField(default=True, help_text='True until catalog-sync replaces with real plugin data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('schema_version', models.CharField(default='v1', max_length=16)),
                ('is_placeholder', models.BooleanField(default=True, help_text='True until catalog-sync replaces with real plugin data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('schema_version', models.CharField(default='v1', max_length=16)),
                ('voicing_style_tag_affinity', models.JSONField(blank=True, default=dict)),
                ('rhythmic_signature', models.JSONField(blank=True, default=dict)),
                ('harmonic_signature', models.JSONField(blank=True, default=dict)),
                ('divergence_notes', models.JSONField(blank=True, default=list)),
                ('is_placeholder', models.BooleanField(default=True, help_text='True until catalog-sync replaces with real plugin data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='StylePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idiom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='styles.idiom')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='styles.master')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='styles.style')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='StyleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('backing_preset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backing_selections', to='styles.stylepreset')),
                ('target_preset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_selections', to='styles.stylepreset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Critique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_match_score', models.FloatField(help_text='0.0–1.0: how well the detected playing matches target_preset.')),
                ('detected_axes', models.JSONField(default=dict, help_text="Comparator's read on what the user is ACTUALLY playing: { 'master': {'slug': ..., 'confidence': ...},   'style': {'slug': ..., 'confidence': ...},   'idiom': {'slug': ..., 'confidence': ...} }")),
                ('commentary', models.TextField(blank=True, help_text='Structured commentary draft — divergence quotes + diagnostics. LLM coach (sub-5) renders these into prose later.')),
                ('audio_input_ref', models.CharField(blank=True, help_text='Opaque reference to the audio passage. sub-4 populates.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critiques', to='styles.styleselection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
