# Generated by Django 5.2.14 on 2026-06-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiom',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Plugin-side fields not modelled as columns yet — prescriptive_lessons, example_masters, diagnostic_examples, etc. sync_plugin_catalogs writes the whole non-mapped subset here so consumers can read it via the .extra accessor without us having to migrate every time the plugin schema grows.'),
        ),
        migrations.AddField(
            model_name='master',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Plugin-side fields not modelled as columns yet — prescriptive_lessons, example_masters, diagnostic_examples, etc. sync_plugin_catalogs writes the whole non-mapped subset here so consumers can read it via the .extra accessor without us having to migrate every time the plugin schema grows.'),
        ),
        migrations.AddField(
            model_name='style',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Plugin-side fields not modelled as columns yet — prescriptive_lessons, example_masters, diagnostic_examples, etc. sync_plugin_catalogs writes the whole non-mapped subset here so consumers can read it via the .extra accessor without us having to migrate every time the plugin schema grows.'),
        ),
    ]
