# Generated by Django 5.2.14 on 2026-06-11 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charts', '0001_initial'),
        ('styles', '0002_idiom_extra_master_extra_style_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackingTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('biab', 'Band-in-a-Box'), ('ireal-pro', 'iReal Pro'), ('custom', 'Custom (user-uploaded)'), ('other', 'Other')], default='other', max_length=32)),
                ('audio_ref', models.CharField(blank=True, help_text='Opaque storage reference (URL / digest). Storage layer TBD.', max_length=512)),
                ('tempo_bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=8)),
                ('time_signature', models.CharField(blank=True, default='4/4', max_length=8)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idiom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backing_tracks', to='styles.idiom')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backing_tracks', to='charts.song')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backing_tracks', to='styles.style')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('backing_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to='practice.backingtrack')),
                ('song', models.ForeignKey(blank=True, help_text='Optional — practice can be open-ended (no specific chart).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to='charts.song')),
                ('target_preset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_practice_sessions', to='styles.stylepreset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ref', models.CharField(help_text='Opaque storage reference for the raw audio file.', max_length=512)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Populated when the recording is finalized.', null=True)),
                ('sample_rate_hz', models.PositiveIntegerField(blank=True, null=True)),
                ('channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='practice.practicesession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ms', models.PositiveIntegerField()),
                ('end_ms', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('critique', models.ForeignKey(blank=True, help_text='Optional — segments can exist before the comparator runs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_segments', to='styles.critique')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='practice.practicesession')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='practice.recording')),
            ],
            options={
                'ordering': ['session', 'start_ms'],
            },
        ),
        migrations.CreateModel(
            name='ChordDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat_timestamp_ms', models.PositiveIntegerField(help_text='Offset from recording start in milliseconds.')),
                ('detected_chord_symbol', models.CharField(max_length=32)),
                ('confidence', models.FloatField(help_text='0.0–1.0 detection confidence.')),
                ('voicing_style_tags', models.JSONField(blank=True, default=list, help_text="List[str]. Empty when sub-4 can't map the detection to known tags.")),
                ('detection_model_ref', models.CharField(blank=True, help_text='Opaque tag identifying the recognizer + version.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chord_detections', to='practice.recording')),
            ],
            options={
                'ordering': ['recording', 'beat_timestamp_ms'],
                'indexes': [models.Index(fields=['recording', 'beat_timestamp_ms'], name='practice_ch_recordi_bd4f50_idx')],
            },
        ),
        migrations.CreateModel(
            name='AudioStem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem_type', models.CharField(choices=[('guitar', 'Guitar'), ('bass', 'Bass'), ('drums', 'Drums'), ('vocals', 'Vocals'), ('keys', 'Keys'), ('other', 'Other')], max_length=16)),
                ('file_ref', models.CharField(max_length=512)),
                ('separation_model_ref', models.CharField(blank=True, help_text="Opaque tag identifying the separator + version that produced this stem. e.g. 'demucs-htdemucs:v4', 'spleeter:5stems'.", max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stems', to='practice.recording')),
            ],
            options={
                'ordering': ['recording', 'stem_type'],
                'constraints': [models.UniqueConstraint(fields=('recording', 'stem_type', 'separation_model_ref'), name='unique_stem_per_recording_type_model')],
            },
        ),
    ]
