# Generated by Django 5.2.14 on 2026-06-18 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_teacher_student_acknowledgement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(help_text='Recipient email address — where the invite was sent.', max_length=254),
        ),
        migrations.AlterField(
            model_name='invite',
            name='expires_at',
            field=models.DateTimeField(help_text='Token expiry. Default 30 days from creation; set by the form layer, NOT by a model default, so the expiry window is visible at the call site.'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='name_hint',
            field=models.CharField(blank=True, help_text='Optional display name for the recipient, used in the invite email body.', max_length=128),
        ),
        migrations.AlterField(
            model_name='recordingcomment',
            name='author',
            field=models.ForeignKey(help_text='Comment author. PROTECT — sentinel-anonymize on user delete via apps.core.delete_user_account.', on_delete=django.db.models.deletion.PROTECT, related_name='recording_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recordingcomment',
            name='body',
            field=models.TextField(help_text='Plain-text comment body. Markdown / rich text is v2.'),
        ),
        migrations.AlterField(
            model_name='recordingcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Soft-delete marker. When set, body is redacted and the comment renders as '[deleted]'. Setting preserves thread shape so replies still anchor.", null=True),
        ),
        migrations.AlterField(
            model_name='recordingshare',
            name='invite',
            field=models.ForeignKey(blank=True, help_text='The Invite this share is waiting on. Null once the invitee has signed up; recipient is set then.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchored_shares', to='practice.invite'),
        ),
        migrations.AlterField(
            model_name='recordingshare',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text="The User who can see the Recording. Null until an anchored Invite is redeemed; backfilled then. PROTECT so account deletion via the sentinel-user repoint preserves the share's audit shape.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recording_shares_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recordingshare',
            name='share_note',
            field=models.TextField(blank=True, help_text='Optional message the sharer attached.'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='slug',
            field=models.SlugField(help_text='URL-safe identifier (lowercase, hyphens, no spaces).', max_length=64, unique=True),
        ),
    ]
